openapi: 3.0.3
info:
  title: AskmeBoard 1.0.0
  description: |-
    sample description
 
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:5000/api/v1
    description: Dev
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
  - url: http://production-api.example.com
    description: Optional server description, e.g. Internal staging server for production
paths:
  /bo/users/create/list/read:
    get:
      summary: Returns a list of users.
      description: bo ดูข้อมูล user เป็น list
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
               $ref: '#/components/schemas/users'
                  
components:
  schemas:
    users:
      description: table.users
      type: object
      properties:
        u_id:
          type: integer
          example: 4
        u_uid:
          type: string
          example: f3%21l|5m235
        u_username:
          type: string
          example: amblotto123
        u_password:
          type: string
          example: amblotto123
        u_phone_number:
          type: string
          example: 0612039510
        u_created_at:
          type: string
          example: 2024-07-24T00:00:00+07:00
        u_updated_at:
          type: string
          example: 2024-07-24T00:00:00+07:00
      # Both properties are required
      required:  
        - u_id
        - name
    admins:
      description: table.admins
      type: object
      properties:
        ad_id:
          type: integer
          example: 4
        ad_users_u_id:
          type: integer
          example: 4
        ad_permission:
          type: integer
          example: ADMIN
        ad_created_at:
          type: string
          example: 2024-07-24T00:00:00+07:00
        ad_updated_at:
          type: string
          example: 2024-07-24T00:00:00+07:00
    ADMIN_PERMISSION:
      type: string
      description: ENUM ADMIN_PERMISSION
      enum:
        - SUPER_ADMIN
        - ADMIN
        
    